### ISSUE TITLE
having an issue with scraper ManyVids: http error 400:Bad Request

### ISSUE THREAD

**Issue by luzersdev** [stashapp/CommunityScrapers#1974] opened 2024-08-15 03:20 UTC
Are you scraping a scene, gallery, movie, or performer?
scraping a movie, trying to generate this video, but I can't create the movie itself.

Scrape with URL? If so, what URLs have you tried?  
https://www.manyvids.com/Video/5856413/gimmel-fucked-frieren-who-was-stuck-in-a-mimic

**Comment by Maista6969** [comment] 2024-08-16 00:14
I am unable to reproduce your issue: scraping the URL you provided works as expected
![bilde](https://github.com/user-attachments/assets/18d5e90f-1f3e-4322-b0ca-215a04c0c6db)

Your also mention that you're trying to create a movie: the ManyVids scraper only supports scenes at this time

And this might be my misunderstanding here, but if you're expecting the scraper to download the actual video file from ManyVids that's not how Stash scrapers work: they will only ever fetch metadata such as the title, date, description etc.

**Comment by toomanynights** [comment] 2024-08-16 04:30
Actually I'm having the same problem :( I installed Manyvids scraper from UI. Trying to scrape a scene by the title. Getting "scraper ManyVids: http error 400:Bad Request" without any further details. Checked yml, it doesn't seem to require anything special, yet I do have python and all required modules installed.

**Comment by Maista6969** [comment] 2024-08-16 11:13
I am still unable to reproduce that error, searching works as expected
![bilde](https://github.com/user-attachments/assets/52f64dd5-7396-4b84-989d-ab9762c992fd)

You mention Python but the updated ManyVids scraper doesn't require Python, are you sure you're using the latest version?

**Comment by toomanynights** [comment] 2024-08-16 11:17
I upgraded to the latest version just this morning. It doesn't seem to require python, still getting the error though.2:14 pm, 16 August 2024, Maista ***@***.***>:
I am still unable to reproduce that error, searching works as expected
bilde.png (view on web)
You mention Python but the updated ManyVids scraper doesn't require Python, are you sure you're using the latest version?

**Comment by Maista6969** [comment] 2024-08-16 11:21
You say "by title", but you mention the Scrape button which scrapes by fragment: do you mean that you're using the query button?
![image](https://github.com/user-attachments/assets/68041e0f-8209-4547-baa5-ebc74a05b403)

If you're clicking "Scrape with..." and selecting ManyVids it will fail unless your filename contains the 6-to-8 digit video code: unfortunately there's no way in the current UI to communicate such a scraper failure, it will just give a cryptic network error in most cases 😦

**Comment by toomanynights** [comment] 2024-08-16 11:51
No, I don't use query button, just "Scrape with...".So you're saying I should use the query button, and provide scene title, right?2:22 pm, 16 August 2024, Maista ***@***.***>:
You say "by title", but you mention the Scrape button which scrapes by fragment: do you mean that you're using the query button?
bilde.png (view on web)
If you're clicking "Scrape with..." and selecting ManyVids it will fail unless your filename contains the 6-to-8 digit video code: unfortunately there's no way in the current UI to communicate such a scraper failure, it will just give a cryptic network error in most cases 😦

**Comment by Maista6969** [comment] 2024-08-16 11:53
> So you're saying I should use the query button, and provide scene title, right?

Yes, that should work 🙂

**Comment by toomanynights** [comment] 2024-08-16 12:19
Got it, thanks - I'll try it!2:54 pm, 16 August 2024, Maista ***@***.***>:

So you're saying I should use the query button, and provide scene title, right?

Yes, that should work 🙂

**Comment by toomanynights** [comment] 2024-08-16 18:51
That worked, thanks!

**Comment by Maista6969** [comment] 2024-08-26 23:41
Closing this since I am unable to reproduce the issue, please reopen with further details if you still have this problem

**Closed by Maista6969** 2024-08-26 23:41 UTC
Labels: bug
