### ISSUE TITLE
Pornhub scraper issue

### ISSUE THREAD

**Issue by mxia9416** [stashapp/CommunityScrapers#1683] opened 2024-03-07 16:03 UTC
Hi all,
When I try to scrape with the community scraper for pornhub and pornhubPremium, I got error message as follow:

>  scraper PornhubPremium: Get "http://my public IP": dial tcp my public IP:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

I don't know if the issue is on my part or pornhub's part? Should I open a port or do a port forwarding of some sort?
Some additional information that may relate to this issue and maybe helpful:

1. the stashdb.org(default) scraper works.
2. community Brazzers scraper works.
3. my port 80 is reported closed using https://www.yougetsignal.com/tools/open-ports/
4. UPNP is disabled for my router
5. tried to set port forwarding 80 to 80 (PC to router) that didn't work
6. I'm new to networking/router stuff so I could be wrong with port forwarding settings (as in it's still closed but I think it was set to open)

**Comment by Maista6969** [comment] 2024-03-07 16:10
How are you scraping? If you're scraping from the scene edit page: do you input an URL and hit the scrape button, are you using "Scrape with..." and selecting "Pornhub", or are you hitting the looking glass button and selecting "Pornhub"?

You mention two different scrapers and I can only really test the Pornhub once since I don't have an account with Pornhub Premium

**Comment by mxia9416** [comment] 2024-03-07 16:29
Hi, what I usually do is: once scenes are added after scanning, I just filter "not organized" scenes, click Tagger and then Scrape All. The above proceture always worked for "professional" scenes. 
These days I try to import “amateur” scenes sourced from Pornhub, In this case, I change Source on the top left to Pornhub and then Scrape All or Search All, which returns the error I posted.
I just tried individual scraping as you described, same error occured with "Scrape with..." option. The URL I put in is the pornhub page of that scene, is this correct?
Only pornhub is fine, ignore the Premium as I was just testing and trying my luck.

**Comment by Maista6969** [comment] 2024-03-07 16:43
That's how I do it as well, but there's an important caveat with the Pornhub scraper: the filename needs to contain the Pornhub ID for the scene, like `ph5cd030d434130`.

All scrapers need some way to connect your local file to a resource on the remote site: the built-in Stash-box scraping feature can use something called a perceptual hash, which is why StashDB/FansDB/PMVStash etc. can match your scene no matter what the filename is.

Other scrapers usually fall back to the filename, like the Pornhub scraper, or the title (which will just be the filename if the scene doesn't have a title), or sometimes the URL (if the scene already has one)

The error you're reporting is an odd one though, I cannot reproduce it in my local Stash: I either get a 404 (when the filename contains something that looks like a Pornhub ID but isn't, like a date) or a "No results found"
![bilde](https://github.com/stashapp/CommunityScrapers/assets/131594657/15e08daa-8179-4a7e-afd7-b4ee1f02b675)

**Comment by mxia9416** [comment] 2024-03-07 17:10
Yeah, I understand the 404 or No results found, they both successfully connect to Pornhub but failed as it's not a proper searching. I just tried search with IDs start with phxxxxxxxxx, no luck. In my case it seems it never made a successful connection with Pornhub as the error message says no respond/timeout. So my first guess was my own networking/router/PC settings, however, I can definitely visit Pornhub using Chrome, so I don't know why Stash can't. That's wired.
Anyways, thank you for walking me through this, I'll try again later.

**Comment by Maista6969** [comment] 2024-03-07 17:12
The filename needs to contain the phxxxxxxxxx, not the search :)

I'll close this for now, but feel free to reopen this (or another issue) if you're having trouble with scrapers

**Closed by Maista6969** 2024-03-07 17:12 UTC

**Comment by mxia9416** [comment] 2024-03-07 19:49
Just a follow up, I try to deploy Stash on my laptop and the Pornhub scraper works! I can now confirm it's due to my PC's setting, unfortunately I can't locate the exact spot. I will just use my laptop for the Pornhub scraping.
